### ISSUE TITLE
Does it handle left-recurred rules?

### ISSUE THREAD

**Issue by blasterinblack** [almondtools/antlr4multichannel#1]
I'm testing your solution (thanks a lot for it!) and it seems to be causing trouble when enable/disable is called from within left-recurred rules; e.g:

`
expression:
   @init {
      enable(Token.HIDDEN_CHANNEL);
   }
   @after {
      disable(Token.HIDDEN_CHANNEL);
   }
   expression WS+ '*' WS+ expression
   | expression WS+ '+' WS+ expression
   | ID
   ;
`
That grammar fails for "x * y + y".

I will be doing some tests to find more what's wrong and keep you informed.

**Comment by almondtools** [comment]
The problem is recursion - not left recursion. Your expression is compiled to:

    {enable}{enable}{enable}x{disable} * {enable}y{disable}{disable} + {enable}y{disable}{disable}

The generator will be equivalent to:

    {enable}x{disable} * {enable}y{disable} + {enable}y{disable}

Yet this is exactly the result you do not expect (whitespace is ignored!).

However I fear a reentrant variant of enable/disable (meaning one that skips enable/disable pairs in enabled blocks and disable/enable pairs in disabled blocks) would raise quite more problems.

Your grammar could be easily rewritten to one that fits your expectations:

    expression_with_whitespace: @init { enable(Token.HIDDEN_CHANNEL); } @after { disable(Token.HIDDEN_CHANNEL); } expression;
    
    expression : expression WS+ '*' WS+ expression | expression WS+ '+' WS+ expression | ID ;

Do you agree?

**Comment by blasterinblack** [comment]
Thanks very much for your prompt reply. My bad that I did not see the problem yesterday - you are very right, the problem is obviously recursion.

Yes, that workaround wil do fine in my case.

Again, thanks a lot!
